# Generated by Django 5.0.4 on 2024-05-22 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("pwd", models.CharField(max_length=15)),
                (
                    "date_inscription",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 5, 22, 15, 39, 2, 650251)
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Livre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=20)),
                ("auteur", models.CharField(max_length=15)),
                ("categorie", models.CharField(max_length=15)),
                ("nombre_pages", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_etudiant", models.IntegerField()),
                ("id_livre", models.IntegerField()),
                (
                    "date_reservation",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 5, 22, 15, 39, 2, 650717)
                    ),
                ),
            ],
        ),
    ]
