# Generated by Django 4.2.6 on 2023-10-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=20)),
                ('auteur', models.CharField(max_length=15)),
                ('categorie', models.CharField(max_length=15)),
                ('nombre_pages', models.IntegerField()),
            ],
        ),
    ]
